# -*- coding: utf-8 -*-
"""Yolo Pedestrian Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtJYmMy8y3AGgP1gCmHvx9tphfLxD96A
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/drive/MyDrive/
if not os.path.isdir("Pedestrian_Crossing_Training"):
  os.makedirs("Pedestrian_Crossing_Training")

# Commented out IPython magic to ensure Python compatibility.
# %cd Pedestrian_Crossing_Training

!git clone https://github.com/WongKinYiu/yolov7
#!pip install -r requirements.txt

"""## **Training**"""

!pwd

cd yolov7

!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

!python train.py --device 0 --batch-size 16 --epochs 100 --img 640 640 --data data/custom_data.yaml --hyp data/hyp.scratch.custom.yaml --cfg cfg/training/yolov7-custom.yaml --weights yolov7.pt --name yolov7-custom

"""### **Testing**"""

!python detect.py --weights runs/train/yolov7-custom3/weights/best.pt --conf 0.40 --img-size 640 --source /content/drive/MyDrive/Pedestrian_Crossing_Training/yolov7/inputimagesall --no-trace

!python detect.py --weights runs/train/best.pt --conf 0.40 --img-size 640 --source /content/drive/MyDrive/Pedestrian_Crossing_Training/yolov7/inputimagesall --no-trace